name: sm_service
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0
  f_datetimerangepicker: ^0.1.4
#  file_picker: ^2.1.0
  provider: ^4.0.2
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  quiver: ^2.0.5
  flutter_login: ^1.0.14
  sqflite: ^1.3.1
  path_provider: ^1.5.1
  get_ip: ^0.4.0
  http: ^0.12.1
  loading_animations: ^2.1.0
  timeline_tile: ^0.1.2
  google_fonts: ^1.1.1
  hexcolor: ^1.0.6
  modal_progress_hud: ^0.1.3
  weather_icons: ^2.0.1
  flutter_showcase: ^0.1.0
  flutter_launcher_icons: ^0.7.5
  rflutter_alert: ^1.0.3
  custom_switch: ^0.0.1
  flutter_email_sender: ^3.0.1
  mailer: ^3.2.1
  cool_alert: ^1.0.1
  date_time_picker: "^1.0.2"
  flutter_holo_date_picker: ^0.2.1
  flutter_isolate: ^1.0.0+14
  flutter_startup: ^0.0.2
  mobile_popup: ^1.2.0




flutter_icons:
  image_path: "assets/ecorp.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/
    - assets/bottomicon/
    - assets/ui/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400